# PROJECT_ROOT is automatically discovered in config.py
DATA_PATH: "{PROJECT_ROOT}/data/user_trials/biased_train"
TEST_PATH: "{PROJECT_ROOT}/data/user_trials/biased_test"
MODELS_PATH: "{PROJECT_ROOT}/trained_models"
ENABLE_CACHING: False
CACHE_DIRECTORY: "{PROJECT_ROOT}/data/.preprocessing_cache"

YAWN_TIME: 5.9       # time, in seconds, an individual yawn lasts for
YAWN_CORRECTION: 0   # account for the delay between the recognisable part of a yawn and pressing it
TIME_DISTRIBUTION: 2 # the number of windows time distribution layers are applied to

TRAIN_SPLIT: 1       # fraction of data to use for training