# PROJECT_ROOT is automatically discovered in config.py
DATA_PATH: "{PROJECT_ROOT}/data/user_trials/train_set"
TEST_PATH: "{PROJECT_ROOT}/data/user_trials/test_set"
MODELS_PATH: "{PROJECT_ROOT}/trained_models"
ENABLE_CACHING: False
CACHE_DIRECTORY: "{PROJECT_ROOT}/data/.preprocessing_cache"

FILE_FORMAT: "csv" # "eimu" or "csv" (hafar-style)
HAFAR_PATH: "{PROJECT_ROOT}/data/HAFAR/files"
# HAFAR_USERS: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] # all users
# HAFAR_USERS: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] # train set
HAFAR_USERS: [17, 18, 19, 20, 21, 22, 23] # test set

YAWN_TIME: 2           # time, in seconds, an individual yawn lasts for
YAWN_CORRECTION: 0     # account for the delay between the recognisable part of a yawn and pressing it
TIME_DISTRIBUTION: 2   # the number of windows time distribution layers are applied to

TRAIN_SPLIT: 1         # fraction of total data to use for training (including validation)
VALIDATION_SPLIT: 0.1  # fraction of total data to use for validation