# PROJECT_ROOT is automatically discovered in config.py
DATA_PATH: "{PROJECT_ROOT}/data/user_trials"
MODELS_PATH: "{PROJECT_ROOT}/trained_models"
ENABLE_CACHING: False
CACHE_DIRECTORY: "{PROJECT_ROOT}/data/.preprocessing_cache"

YAWN_TIME: 5.9        # time, in seconds, an individual yawn lasts for
YAWN_CORRECTION: 0  # account for the delay between the recognisable part of a yawn and pressing it

TRAIN_SPLIT: 0.8    # fraction of data to use for training